language: r
cache: packages
pandoc_version: 1.19.2.1

r_github_packages:
  - rethomics/behavr
  - rethomics/scopr
  - rethomics/damr
  - rethomics/sleepr
  - rethomics/zeitgebr
  - rethomics/ggetho


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh

after_success:
  - ./_deploy.sh

branches:
  only:
  - source
